import { randomUUID } from 'crypto';
import { NextRequest, NextResponse } from 'next/server';
import pool from '@/lib/db';
import { adjustWallet } from '@/lib/services/wallet';
import { TransactionRepository } from '@/lib/providers/repositories/TransactionRepository';
import { GamingActivityService } from '@/lib/services/gaming-activity';
import { GamingEventType } from '@/lib/providers/types/metadata.types';

const SYSTEM_ADMIN_ID = parseInt(process.env.GAME_SYSTEM_ADMIN_ID ?? '1', 10);
const txRepo = new TransactionRepository();

/**
 * POST /api/games/confirm-play  (Internal service API)
 *
 * Executes the Transfer In (wallet deduction + provider topUp) for TRANSFER
 * wallet providers. Called by the website when the member clicks "Main Sekarang"
 * in the App dialog, after credentials have already been shown.
 *
 * Auth: X-Service-Secret header must match REVALIDATE_SECRET env var.
 *
 * Body:
 *   { user_id, provider_code, confirm_ref_id }
 *
 * confirm_ref_id: UUID generated by /api/games/launch and embedded in
 *   session_token. Used as the idempotency key — a second call with the
 *   same confirm_ref_id returns { ok: true, already_completed: true }
 *   without touching the wallet again.
 *
 * Response:
 *   200 { ok: true }                         — Transfer In succeeded
 *   200 { ok: true, already_completed: true } — already done (idempotent)
 *   409                                       — concurrent call in progress
 *   422                                       — insufficient balance
 *   502                                       — topUp failed (balance restored)
 *
 * Duplicate-request protection (layered):
 *   1. Pre-check: query provider_transactions for existing SUCCESS with this confirm_ref_id.
 *   2. Concurrent lock: pg_try_advisory_xact_lock(user_id) serialises simultaneous calls.
 *   3. Post-lock re-check: handles the race between pre-check and lock acquisition.
 *   4. adjustWallet FOR UPDATE: balance reads are always serialised at DB level.
 *   5. autoWithdrawAll: recovers any funds already in provider before re-deducting.
 */
export async function POST(req: NextRequest) {
  // ── Service-to-service auth ──────────────────────────────────────────────
  const secret = process.env.REVALIDATE_SECRET;
  if (!secret || req.headers.get('x-service-secret') !== secret) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  let body: { user_id?: number; provider_code?: string; confirm_ref_id?: string };
  try { body = await req.json() as typeof body; }
  catch { return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 }); }

  const { user_id, provider_code, confirm_ref_id } = body;
  if (!user_id || !provider_code || !confirm_ref_id) {
    return NextResponse.json(
      { error: 'user_id, provider_code, confirm_ref_id are required' },
      { status: 400 },
    );
  }

  const upperCode = provider_code.toUpperCase();

  // ── 1. Load user ──────────────────────────────────────────────────────────
  const { rows: userRows } = await pool.query<{ id: number }>(
    `SELECT id FROM users WHERE id = $1 LIMIT 1`,
    [user_id],
  );
  if (!userRows[0]) return NextResponse.json({ error: `User ${user_id} not found` }, { status: 404 });

  // ── 2. Load provider + adapter ────────────────────────────────────────────
  let adapter: import('@/lib/providers').IGameProvider;
  let gpProviderId: number;
  let walletType: string;

  {
    const { rows: bpFindRows } = await pool.query<{ brand_code: string }>(
      `SELECT b.code AS brand_code
       FROM brand_providers bp
       JOIN brands      b ON b.id  = bp.brand_id
       JOIN gp_providers p ON p.id = bp.provider_id
       WHERE UPPER(p.code) = $1
         AND bp.status IN ('ACTIVE', 'TESTING')
       ORDER BY (bp.status = 'ACTIVE') DESC, bp.id ASC
       LIMIT 1`,
      [upperCode],
    );

    if (!bpFindRows[0]) {
      return NextResponse.json(
        { error: `Provider "${upperCode}" is not active` },
        { status: 503 },
      );
    }

    const activeBrandCode = bpFindRows[0].brand_code;

    const { createGamingPlatform, ProviderRepository } = await import('@/lib/providers');
    const { ProviderRuntimeBuilder } = await import('@/lib/providers/core/ProviderRuntimeBuilder');
    const platform     = createGamingPlatform();
    const providerRepo = new ProviderRepository();

    const result = await ProviderRuntimeBuilder.build(
      activeBrandCode,
      upperCode,
      (v) => platform.security.decrypt(v),
      { wallet: platform.wallet, eventLogger: platform.eventLogger, providerRepo },
      false,
    );

    if (!result.found || !result.adapterBuilt || !result.adapter) {
      return NextResponse.json(
        { error: `Provider "${upperCode}" could not be initialized` },
        { status: 503 },
      );
    }

    gpProviderId = result.gpProviderId;
    walletType   = result.bpWalletType;
    adapter      = result.adapter;
  }

  // ── 3. Verify TRANSFER wallet ─────────────────────────────────────────────
  if (walletType !== 'TRANSFER') {
    return NextResponse.json(
      { error: `${upperCode} uses ${walletType} wallet — confirm-play is only for TRANSFER wallet providers` },
      { status: 400 },
    );
  }

  // ── 4. Load player record ─────────────────────────────────────────────────
  const { rows: playerRows } = await pool.query<{
    id: number; provider_player_id: string | null; provider_account_id: string;
  }>(
    `SELECT id, provider_player_id, provider_account_id
     FROM gp_players WHERE provider_id = $1 AND user_id = $2 LIMIT 1`,
    [gpProviderId, user_id],
  );
  const playerRecord = playerRows[0];
  if (!playerRecord) {
    return NextResponse.json(
      { error: 'Player account not found. Launch the game first to register.' },
      { status: 404 },
    );
  }

  const loginId = playerRecord.provider_player_id;
  if (!loginId) {
    return NextResponse.json(
      { error: 'Provider account is not fully initialized' },
      { status: 503 },
    );
  }

  // ── 5. Idempotency pre-check ──────────────────────────────────────────────
  // If this confirm_ref_id already has a SUCCESS FUND_REQUEST, return immediately.
  // This handles the network-retry case: topUp succeeded but HTTP response was lost.
  const existingTxs = await txRepo.findByReferenceId(upperCode, confirm_ref_id);
  const alreadyDone = existingTxs.some(tx => tx.type === 'FUND_REQUEST' && tx.status === 'SUCCESS');
  if (alreadyDone) {
    console.log(`[games/confirm-play] confirm_ref_id=${confirm_ref_id} already SUCCESS — returning ok`);
    return NextResponse.json({ ok: true, already_completed: true });
  }

  // ── 6. Concurrent-request lock ────────────────────────────────────────────
  // pg_try_advisory_xact_lock returns false immediately if another transaction
  // holds the same lock, preventing two simultaneous confirm-play calls from
  // the same user from both proceeding to the deduction step.
  const lockClient = await pool.connect();
  try {
    await lockClient.query('BEGIN');

    const { rows: lockRows } = await lockClient.query<{ result: boolean }>(
      `SELECT pg_try_advisory_xact_lock($1) AS result`,
      [user_id],
    );
    if (!lockRows[0]?.result) {
      await lockClient.query('ROLLBACK');
      return NextResponse.json(
        { error: '正在处理中，请勿重复操作' },
        { status: 409 },
      );
    }

    // Post-lock re-check — handles the race between pre-check and lock acquisition
    const txsAfterLock = await txRepo.findByReferenceId(upperCode, confirm_ref_id);
    const doneAfterLock = txsAfterLock.some(tx => tx.type === 'FUND_REQUEST' && tx.status === 'SUCCESS');
    if (doneAfterLock) {
      await lockClient.query('ROLLBACK');
      console.log(`[games/confirm-play] confirm_ref_id=${confirm_ref_id} done (post-lock check) — returning ok`);
      return NextResponse.json({ ok: true, already_completed: true });
    }

    // We hold the advisory lock; commit the lock transaction so the lock is
    // released cleanly (xact-level locks release on COMMIT/ROLLBACK).
    await lockClient.query('COMMIT');
  } catch (lockErr) {
    await lockClient.query('ROLLBACK').catch(() => undefined);
    throw lockErr;
  } finally {
    lockClient.release();
  }

  // ── 7. Transfer Wallet: autoWithdrawAll + Transfer In ────────────────────
  const ts = Date.now();

  type XferAdapter = {
    topUp:            (p: { provider_player_id: string; amount: number; reference_id: string; currency: string }) => Promise<{ balance: number }>;
    autoWithdrawAll?: (loginId: string) => Promise<number>;
  };
  const xferAdapter = adapter as unknown as XferAdapter;

  // ── Step A: autoWithdrawAll — protect against the gap between dialog open ─
  // and MAIN SEKARANG click. If the provider already has a balance (e.g. from
  // the autoWithdrawAll in launch that partially failed, or a concurrent session),
  // recover it first so we don't double-fund the provider.
  let recovered = 0;
  if (typeof xferAdapter.autoWithdrawAll === 'function') {
    try {
      recovered = await xferAdapter.autoWithdrawAll(loginId);
      console.log(`[games/confirm-play] autoWithdrawAll recovered=${recovered}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes('37123')) {
        console.log(`[games/confirm-play] provider wallet already empty (37123) — OK`);
      } else {
        console.warn(`[games/confirm-play] autoWithdrawAll error (non-fatal): ${msg}`);
      }
    }
  }

  if (recovered > 0) {
    const wdRefId  = `${upperCode}WD-CONFIRM-${user_id}-${ts}`;
    const wdClient = await pool.connect();
    try {
      await wdClient.query('BEGIN');
      const wtRow = await adjustWallet(wdClient, {
        userId:          user_id,
        type:            'PAYMENT_GATEWAY',
        direction:       'C',
        amount:          recovered,
        gateway:         upperCode,
        referenceNumber: wdRefId,
        remark:          `[${upperCode}] Transfer Out (before Confirm Play)`,
        operatorAdminId: SYSTEM_ADMIN_ID,
      });
      await wdClient.query('COMMIT');
      const wdBefore = parseFloat(wtRow.balance_before);
      const wdAfter  = parseFloat(wtRow.balance_after);
      console.log(`[games/confirm-play] ✓ recovered ${recovered}: wallet ${wdBefore} → ${wdAfter}`);

      await txRepo.create({
        provider:       upperCode,
        transaction_id: wtRow.id,
        reference_id:   wdRefId,
        type:           'FUND_RETURN',
        status:         'SUCCESS',
        user_id,
        user_public_id: playerRecord.provider_account_id,
        amount:         recovered,
        currency:       'MYR',
        before_balance: wdBefore,
        after_balance:  wdAfter,
        metadata:       { trigger: 'CONFIRM_PLAY', step: 'AUTO_WITHDRAW' },
      }).catch(e => console.warn('[games/confirm-play] provider_transactions write failed:', e));

      void GamingActivityService.record({
        memberId:      user_id,
        providerCode:  upperCode,
        eventType:     GamingEventType.TransferOut,
        amount:        recovered,
        balanceBefore: wdBefore,
        balanceAfter:  wdAfter,
        referenceType: 'wallet_transaction',
        referenceId:   parseInt(wtRow.id, 10) || null,
        operatorType:  'MEMBER',
        operatorId:    user_id,
        metadata:      { ref_id: wdRefId, trigger: 'CONFIRM_PLAY' },
      });
    } catch (e) {
      await wdClient.query('ROLLBACK').catch(() => undefined);
      console.error(`[games/confirm-play] ✗ credit (after autoWithdrawAll) failed:`, e);
    } finally {
      wdClient.release();
    }
  }

  // ── Step B: Read fresh balance + Transfer In ──────────────────────────────
  const { rows: balRows } = await pool.query<{ available_balance: string }>(
    `SELECT available_balance FROM users WHERE id = $1 LIMIT 1`,
    [user_id],
  );
  const balance = parseFloat(balRows[0]?.available_balance ?? '0');
  console.log(`[games/confirm-play] Transfer In: userId=${user_id} balance=${balance} loginId="${loginId}" ref="${confirm_ref_id}"`);

  if (balance <= 0) {
    console.warn(`[games/confirm-play] balance=0 for userId=${user_id} — skipping Transfer In`);
    return NextResponse.json({ ok: true });
  }

  let deductOk  = false;
  let deductWtRow: Awaited<ReturnType<typeof adjustWallet>> | null = null;

  const deductClient = await pool.connect();
  try {
    await deductClient.query('BEGIN');
    deductWtRow = await adjustWallet(deductClient, {
      userId:          user_id,
      type:            'PAYMENT_GATEWAY',
      direction:       'D',
      amount:          balance,
      gateway:         upperCode,
      referenceNumber: confirm_ref_id,
      remark:          `[${upperCode}] Transfer In (Confirm Play)`,
      operatorAdminId: SYSTEM_ADMIN_ID,
    });
    await deductClient.query('COMMIT');
    deductOk = true;
    const balBefore = parseFloat(deductWtRow.balance_before);
    const balAfter  = parseFloat(deductWtRow.balance_after);
    console.log(`[games/confirm-play] ✓ deduction: ${balBefore} → ${balAfter}`);

    await txRepo.create({
      provider:       upperCode,
      transaction_id: deductWtRow.id,
      reference_id:   confirm_ref_id,
      type:           'FUND_REQUEST',
      status:         'PENDING',
      user_id,
      user_public_id: playerRecord.provider_account_id,
      amount:         balance,
      currency:       'MYR',
      before_balance: balBefore,
      after_balance:  balAfter,
      metadata:       { trigger: 'CONFIRM_PLAY', step: 'DEDUCT' },
    }).catch(e => console.warn('[games/confirm-play] provider_transactions write failed:', e));
  } catch (err) {
    await deductClient.query('ROLLBACK').catch(() => undefined);
    console.error(`[games/confirm-play] ✗ deduction failed:`, err);
    const errMsg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: errMsg.includes('Insufficient') ? '余额不足，请充值后再试' : '扣款失败，请稍后再试' }, { status: 422 });
  } finally {
    deductClient.release();
  }

  if (!deductOk || !deductWtRow) {
    return NextResponse.json({ error: '扣款失败，请稍后再试' }, { status: 500 });
  }

  const deductBalBefore = parseFloat(deductWtRow.balance_before);
  const deductBalAfter  = parseFloat(deductWtRow.balance_after);
  let topUpOk    = false;
  let topUpError = '';

  try {
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        console.log(`[games/confirm-play] topUp attempt ${attempt}/3 loginId="${loginId}" amount=${balance}`);
        const topUpResult = await xferAdapter.topUp({
          provider_player_id: loginId,
          amount:             balance,
          reference_id:       confirm_ref_id,
          currency:           'MYR',
        });
        topUpOk = true;
        console.log(`[games/confirm-play] ✓ topUp SUCCESS: provider balance=${topUpResult.balance}`);

        // Record SUCCESS with confirm_ref_id — this is what the idempotency check reads
        await txRepo.create({
          provider:       upperCode,
          transaction_id: randomUUID(),
          reference_id:   confirm_ref_id,
          type:           'FUND_REQUEST',
          status:         'SUCCESS',
          user_id,
          user_public_id: playerRecord.provider_account_id,
          amount:         balance,
          currency:       'MYR',
          before_balance: deductBalBefore,
          after_balance:  topUpResult.balance,
          metadata:       { trigger: 'CONFIRM_PLAY', step: 'TOPUP', provider_balance: topUpResult.balance },
        }).catch(e => console.warn('[games/confirm-play] provider_transactions write failed:', e));

        void GamingActivityService.record({
          memberId:      user_id,
          providerCode:  upperCode,
          eventType:     GamingEventType.TransferIn,
          amount:        balance,
          balanceBefore: deductBalBefore,
          balanceAfter:  deductBalAfter,
          referenceType: 'wallet_transaction',
          referenceId:   parseInt(deductWtRow.id, 10) || null,
          operatorType:  'MEMBER',
          operatorId:    user_id,
          metadata:      { confirm_ref_id, trigger: 'CONFIRM_PLAY' },
        });
        break;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error(`[games/confirm-play] topUp attempt ${attempt} FAILED: ${msg}`);
        if (msg.includes('37153') && attempt < 3) {
          await new Promise(r => setTimeout(r, 3000 * attempt));
          continue;
        }
        topUpError = msg;
        throw err;
      }
    }
  } catch (err) {
    const errMsg = topUpError || (err instanceof Error ? err.message : String(err));
    console.error(`[games/confirm-play] ✗ topUp FAILED — rolling back userId=${user_id} amount=${balance}`);

    const rbClient = await pool.connect();
    try {
      await rbClient.query('BEGIN');
      const rbWtRow = await adjustWallet(rbClient, {
        userId:          user_id,
        type:            'CORRECTION',
        direction:       'C',
        amount:          balance,
        gateway:         upperCode,
        referenceNumber: `${upperCode}CP-ROLLBACK-${user_id}-${ts}`,
        remark:          `[${upperCode}] Rollback (Confirm Play)`,
        operatorAdminId: SYSTEM_ADMIN_ID,
      });
      await rbClient.query('COMMIT');
      console.log(`[games/confirm-play] ✓ rollback complete: balance restored to ${parseFloat(rbWtRow.balance_after)}`);

      void GamingActivityService.record({
        memberId:      user_id,
        providerCode:  upperCode,
        eventType:     GamingEventType.TransferRollback,
        amount:        balance,
        balanceBefore: parseFloat(rbWtRow.balance_before),
        balanceAfter:  parseFloat(rbWtRow.balance_after),
        referenceType: 'wallet_transaction',
        referenceId:   parseInt(rbWtRow.id, 10) || null,
        operatorType:  'SYSTEM',
        operatorId:    SYSTEM_ADMIN_ID,
        metadata:      { error: errMsg.slice(0, 255), confirm_ref_id },
      });
    } catch (rbErr) {
      await rbClient.query('ROLLBACK').catch(() => undefined);
      console.error(`[games/confirm-play] ✗✗ CRITICAL: rollback FAILED userId=${user_id} amount=${balance} — MANUAL INTERVENTION REQUIRED`);
    } finally {
      rbClient.release();
    }

    return NextResponse.json({ error: '游戏充值失败，余额已退回，请重试' }, { status: 502 });
  }

  if (!topUpOk) {
    return NextResponse.json({ error: '游戏充值失败，请重试' }, { status: 502 });
  }

  return NextResponse.json({ ok: true });
}
