-- 073_theme_engine.sql
-- Phase M5-D — Expand all partner themes to 43-variable canonical system
--
-- Canonical variable groups:
--   Brand Colors:   --pb-primary/secondary/accent
--   Backgrounds:    --pb-bg-page/section/section-alt/card/card-hover
--   Header/Footer:  --pb-bg-header / --pb-bg-footer
--   Text:           --pb-text-primary/secondary/muted
--   Borders:        --pb-border / --pb-border-card
--   Buttons:        --pb-btn-bg/text/hover / --pb-btn-outline-color
--   Shadows:        --pb-shadow / --pb-shadow-card / --pb-shadow-glow
--   Shape:          --pb-radius / --pb-radius-card / --pb-radius-btn / --pb-radius-lg
--   Typography:     --pb-font-display/body/size-base/weight-heading/weight-body/line-height/letter-spacing-heading
--   Spacing:        --pb-section-py/px / --pb-card-gap/padding / --pb-container-width
--   Animation:      --pb-duration-fast/base/slow / --pb-easing / --pb-hero-min-height

-- ── 01 Luxury Black Gold ────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#d4a017",
  "--pb-secondary":             "#b8860b",
  "--pb-accent":                "#f5c842",
  "--pb-bg-page":               "#0a0a0a",
  "--pb-bg-section":            "#111111",
  "--pb-bg-section-alt":        "#0d0d0d",
  "--pb-bg-card":               "#1a1a1a",
  "--pb-bg-card-hover":         "#222222",
  "--pb-bg-header":             "#080808",
  "--pb-bg-footer":             "#080808",
  "--pb-text-primary":          "#ffffff",
  "--pb-text-secondary":        "#cccccc",
  "--pb-text-muted":            "#888888",
  "--pb-border":                "rgba(212,160,23,0.2)",
  "--pb-border-card":           "rgba(212,160,23,0.15)",
  "--pb-btn-bg":                "#d4a017",
  "--pb-btn-text":              "#000000",
  "--pb-btn-hover":             "#b8860b",
  "--pb-btn-outline-color":     "#d4a017",
  "--pb-shadow":                "0 4px 24px rgba(0,0,0,0.6)",
  "--pb-shadow-card":           "0 2px 12px rgba(0,0,0,0.5)",
  "--pb-shadow-glow":           "0 0 32px rgba(212,160,23,0.2)",
  "--pb-radius":                "6px",
  "--pb-radius-card":           "10px",
  "--pb-radius-btn":            "5px",
  "--pb-radius-lg":             "16px",
  "--pb-font-display":          "Georgia, ''Times New Roman'', serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "700",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.65",
  "--pb-letter-spacing-heading":"-0.01em",
  "--pb-section-py":            "72px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "20px",
  "--pb-card-padding":          "24px",
  "--pb-container-width":       "1100px",
  "--pb-duration-fast":         "0.15s",
  "--pb-duration-base":         "0.25s",
  "--pb-duration-slow":         "0.5s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "520px"
}'::jsonb
WHERE slug = 'luxury-black-gold';

-- ── 02 MR Green ─────────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#22c55e",
  "--pb-secondary":             "#16a34a",
  "--pb-accent":                "#4ade80",
  "--pb-bg-page":               "#0d1a0d",
  "--pb-bg-section":            "#111f11",
  "--pb-bg-section-alt":        "#0f1c0f",
  "--pb-bg-card":               "#1a2e1a",
  "--pb-bg-card-hover":         "#223a22",
  "--pb-bg-header":             "#091209",
  "--pb-bg-footer":             "#091209",
  "--pb-text-primary":          "#ffffff",
  "--pb-text-secondary":        "#d1fae5",
  "--pb-text-muted":            "#86efac",
  "--pb-border":                "rgba(34,197,94,0.2)",
  "--pb-border-card":           "rgba(34,197,94,0.15)",
  "--pb-btn-bg":                "#22c55e",
  "--pb-btn-text":              "#000000",
  "--pb-btn-hover":             "#16a34a",
  "--pb-btn-outline-color":     "#22c55e",
  "--pb-shadow":                "0 4px 24px rgba(0,0,0,0.5)",
  "--pb-shadow-card":           "0 2px 12px rgba(0,0,0,0.4)",
  "--pb-shadow-glow":           "0 0 28px rgba(34,197,94,0.2)",
  "--pb-radius":                "8px",
  "--pb-radius-card":           "12px",
  "--pb-radius-btn":            "6px",
  "--pb-radius-lg":             "18px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "700",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.6",
  "--pb-letter-spacing-heading":"-0.02em",
  "--pb-section-py":            "64px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "16px",
  "--pb-card-padding":          "20px",
  "--pb-container-width":       "1200px",
  "--pb-duration-fast":         "0.15s",
  "--pb-duration-base":         "0.2s",
  "--pb-duration-slow":         "0.4s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "480px"
}'::jsonb
WHERE slug = 'mr-green';

-- ── 03 Blue Ocean ───────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#38bdf8",
  "--pb-secondary":             "#0ea5e9",
  "--pb-accent":                "#7dd3fc",
  "--pb-bg-page":               "#0c1a2e",
  "--pb-bg-section":            "#0f2040",
  "--pb-bg-section-alt":        "#0d1c38",
  "--pb-bg-card":               "#152744",
  "--pb-bg-card-hover":         "#1d3258",
  "--pb-bg-header":             "#081424",
  "--pb-bg-footer":             "#081424",
  "--pb-text-primary":          "#ffffff",
  "--pb-text-secondary":        "#e0f2fe",
  "--pb-text-muted":            "#7dd3fc",
  "--pb-border":                "rgba(56,189,248,0.2)",
  "--pb-border-card":           "rgba(56,189,248,0.15)",
  "--pb-btn-bg":                "#38bdf8",
  "--pb-btn-text":              "#0c1a2e",
  "--pb-btn-hover":             "#0ea5e9",
  "--pb-btn-outline-color":     "#38bdf8",
  "--pb-shadow":                "0 4px 24px rgba(0,0,0,0.5)",
  "--pb-shadow-card":           "0 2px 12px rgba(0,0,0,0.4)",
  "--pb-shadow-glow":           "0 0 28px rgba(56,189,248,0.2)",
  "--pb-radius":                "10px",
  "--pb-radius-card":           "14px",
  "--pb-radius-btn":            "8px",
  "--pb-radius-lg":             "20px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "700",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.6",
  "--pb-letter-spacing-heading":"-0.02em",
  "--pb-section-py":            "64px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "16px",
  "--pb-card-padding":          "20px",
  "--pb-container-width":       "1200px",
  "--pb-duration-fast":         "0.12s",
  "--pb-duration-base":         "0.2s",
  "--pb-duration-slow":         "0.4s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "480px"
}'::jsonb
WHERE slug = 'blue-ocean';

-- ── 04 Purple Neon ──────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#a855f7",
  "--pb-secondary":             "#9333ea",
  "--pb-accent":                "#d8b4fe",
  "--pb-bg-page":               "#0d0020",
  "--pb-bg-section":            "#130030",
  "--pb-bg-section-alt":        "#100028",
  "--pb-bg-card":               "#1c0040",
  "--pb-bg-card-hover":         "#240055",
  "--pb-bg-header":             "#08001a",
  "--pb-bg-footer":             "#08001a",
  "--pb-text-primary":          "#ffffff",
  "--pb-text-secondary":        "#f3e8ff",
  "--pb-text-muted":            "#c084fc",
  "--pb-border":                "rgba(168,85,247,0.25)",
  "--pb-border-card":           "rgba(168,85,247,0.2)",
  "--pb-btn-bg":                "#a855f7",
  "--pb-btn-text":              "#ffffff",
  "--pb-btn-hover":             "#9333ea",
  "--pb-btn-outline-color":     "#a855f7",
  "--pb-shadow":                "0 4px 32px rgba(0,0,0,0.6)",
  "--pb-shadow-card":           "0 2px 16px rgba(0,0,0,0.5)",
  "--pb-shadow-glow":           "0 0 40px rgba(168,85,247,0.3)",
  "--pb-radius":                "8px",
  "--pb-radius-card":           "12px",
  "--pb-radius-btn":            "6px",
  "--pb-radius-lg":             "18px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "800",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.6",
  "--pb-letter-spacing-heading":"0em",
  "--pb-section-py":            "64px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "16px",
  "--pb-card-padding":          "20px",
  "--pb-container-width":       "1200px",
  "--pb-duration-fast":         "0.1s",
  "--pb-duration-base":         "0.18s",
  "--pb-duration-slow":         "0.35s",
  "--pb-easing":                "cubic-bezier(0.2, 0, 0, 1)",
  "--pb-hero-min-height":       "500px"
}'::jsonb
WHERE slug = 'purple-neon';

-- ── 05 Royal Red ────────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#ef4444",
  "--pb-secondary":             "#dc2626",
  "--pb-accent":                "#fca5a5",
  "--pb-bg-page":               "#1a0000",
  "--pb-bg-section":            "#200000",
  "--pb-bg-section-alt":        "#1c0000",
  "--pb-bg-card":               "#2a0000",
  "--pb-bg-card-hover":         "#350000",
  "--pb-bg-header":             "#140000",
  "--pb-bg-footer":             "#140000",
  "--pb-text-primary":          "#ffffff",
  "--pb-text-secondary":        "#fee2e2",
  "--pb-text-muted":            "#fca5a5",
  "--pb-border":                "rgba(239,68,68,0.2)",
  "--pb-border-card":           "rgba(239,68,68,0.15)",
  "--pb-btn-bg":                "#ef4444",
  "--pb-btn-text":              "#ffffff",
  "--pb-btn-hover":             "#dc2626",
  "--pb-btn-outline-color":     "#ef4444",
  "--pb-shadow":                "0 4px 24px rgba(0,0,0,0.6)",
  "--pb-shadow-card":           "0 2px 12px rgba(0,0,0,0.5)",
  "--pb-shadow-glow":           "0 0 28px rgba(239,68,68,0.25)",
  "--pb-radius":                "6px",
  "--pb-radius-card":           "10px",
  "--pb-radius-btn":            "5px",
  "--pb-radius-lg":             "14px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "800",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.6",
  "--pb-letter-spacing-heading":"-0.01em",
  "--pb-section-py":            "60px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "16px",
  "--pb-card-padding":          "20px",
  "--pb-container-width":       "1100px",
  "--pb-duration-fast":         "0.15s",
  "--pb-duration-base":         "0.22s",
  "--pb-duration-slow":         "0.4s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "480px"
}'::jsonb
WHERE slug = 'royal-red';

-- ── 06 Orange Energy ────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#f97316",
  "--pb-secondary":             "#ea580c",
  "--pb-accent":                "#fdba74",
  "--pb-bg-page":               "#1a0e00",
  "--pb-bg-section":            "#201200",
  "--pb-bg-section-alt":        "#1c1000",
  "--pb-bg-card":               "#2a1800",
  "--pb-bg-card-hover":         "#352000",
  "--pb-bg-header":             "#140a00",
  "--pb-bg-footer":             "#140a00",
  "--pb-text-primary":          "#ffffff",
  "--pb-text-secondary":        "#ffedd5",
  "--pb-text-muted":            "#fdba74",
  "--pb-border":                "rgba(249,115,22,0.2)",
  "--pb-border-card":           "rgba(249,115,22,0.15)",
  "--pb-btn-bg":                "#f97316",
  "--pb-btn-text":              "#ffffff",
  "--pb-btn-hover":             "#ea580c",
  "--pb-btn-outline-color":     "#f97316",
  "--pb-shadow":                "0 4px 24px rgba(0,0,0,0.5)",
  "--pb-shadow-card":           "0 2px 12px rgba(0,0,0,0.4)",
  "--pb-shadow-glow":           "0 0 28px rgba(249,115,22,0.2)",
  "--pb-radius":                "8px",
  "--pb-radius-card":           "12px",
  "--pb-radius-btn":            "7px",
  "--pb-radius-lg":             "18px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "800",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.6",
  "--pb-letter-spacing-heading":"0em",
  "--pb-section-py":            "64px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "16px",
  "--pb-card-padding":          "20px",
  "--pb-container-width":       "1200px",
  "--pb-duration-fast":         "0.12s",
  "--pb-duration-base":         "0.18s",
  "--pb-duration-slow":         "0.35s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "460px"
}'::jsonb
WHERE slug = 'orange-energy';

-- ── 07 Dark Mode ────────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#6366f1",
  "--pb-secondary":             "#4f46e5",
  "--pb-accent":                "#a5b4fc",
  "--pb-bg-page":               "#0f0f0f",
  "--pb-bg-section":            "#141414",
  "--pb-bg-section-alt":        "#111111",
  "--pb-bg-card":               "#1c1c1c",
  "--pb-bg-card-hover":         "#242424",
  "--pb-bg-header":             "#0a0a0a",
  "--pb-bg-footer":             "#0a0a0a",
  "--pb-text-primary":          "#f8fafc",
  "--pb-text-secondary":        "#cbd5e1",
  "--pb-text-muted":            "#64748b",
  "--pb-border":                "rgba(255,255,255,0.08)",
  "--pb-border-card":           "rgba(255,255,255,0.06)",
  "--pb-btn-bg":                "#6366f1",
  "--pb-btn-text":              "#ffffff",
  "--pb-btn-hover":             "#4f46e5",
  "--pb-btn-outline-color":     "#6366f1",
  "--pb-shadow":                "0 4px 24px rgba(0,0,0,0.4)",
  "--pb-shadow-card":           "0 2px 12px rgba(0,0,0,0.35)",
  "--pb-shadow-glow":           "0 0 24px rgba(99,102,241,0.15)",
  "--pb-radius":                "8px",
  "--pb-radius-card":           "12px",
  "--pb-radius-btn":            "6px",
  "--pb-radius-lg":             "16px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "700",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.6",
  "--pb-letter-spacing-heading":"-0.02em",
  "--pb-section-py":            "64px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "16px",
  "--pb-card-padding":          "20px",
  "--pb-container-width":       "1200px",
  "--pb-duration-fast":         "0.15s",
  "--pb-duration-base":         "0.2s",
  "--pb-duration-slow":         "0.4s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "480px"
}'::jsonb
WHERE slug = 'dark-mode';

-- ── 08 White Minimal ────────────────────────────────────────────────────────
UPDATE partner_themes SET css_variables = '{
  "--pb-primary":               "#111827",
  "--pb-secondary":             "#374151",
  "--pb-accent":                "#6366f1",
  "--pb-bg-page":               "#ffffff",
  "--pb-bg-section":            "#f9fafb",
  "--pb-bg-section-alt":        "#f3f4f6",
  "--pb-bg-card":               "#ffffff",
  "--pb-bg-card-hover":         "#f9fafb",
  "--pb-bg-header":             "#ffffff",
  "--pb-bg-footer":             "#f9fafb",
  "--pb-text-primary":          "#111827",
  "--pb-text-secondary":        "#374151",
  "--pb-text-muted":            "#9ca3af",
  "--pb-border":                "#e5e7eb",
  "--pb-border-card":           "#e5e7eb",
  "--pb-btn-bg":                "#111827",
  "--pb-btn-text":              "#ffffff",
  "--pb-btn-hover":             "#374151",
  "--pb-btn-outline-color":     "#111827",
  "--pb-shadow":                "0 2px 12px rgba(0,0,0,0.08)",
  "--pb-shadow-card":           "0 1px 6px rgba(0,0,0,0.06)",
  "--pb-shadow-glow":           "0 0 20px rgba(99,102,241,0.12)",
  "--pb-radius":                "8px",
  "--pb-radius-card":           "12px",
  "--pb-radius-btn":            "6px",
  "--pb-radius-lg":             "16px",
  "--pb-font-display":          "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-body":             "system-ui, -apple-system, ''Segoe UI'', Roboto, sans-serif",
  "--pb-font-size-base":        "16px",
  "--pb-font-weight-heading":   "700",
  "--pb-font-weight-body":      "400",
  "--pb-line-height":           "1.65",
  "--pb-letter-spacing-heading":"-0.025em",
  "--pb-section-py":            "64px",
  "--pb-section-px":            "20px",
  "--pb-card-gap":              "20px",
  "--pb-card-padding":          "24px",
  "--pb-container-width":       "1200px",
  "--pb-duration-fast":         "0.15s",
  "--pb-duration-base":         "0.2s",
  "--pb-duration-slow":         "0.4s",
  "--pb-easing":                "cubic-bezier(0.4, 0, 0.2, 1)",
  "--pb-hero-min-height":       "440px"
}'::jsonb
WHERE slug = 'white-minimal';
