-- ═══════════════════════════════════════════════════════════════════════════════
-- Migration 093: Gaming Provider Framework Phase 3 — Database Preparation
--
-- Prepares the database layer for the Gaming Activity Framework (Task 1+).
--
-- Changes:
--   1. member_activity_logs — ADD trace_id column (Activity Timeline Principle)
--   2. gp_providers — SET metadata initial values for MEGAAPP, MEGAH5, 918KISS
--
-- Category note:
--   member_activity_logs.category is VARCHAR(30) with no CHECK constraint.
--   New categories 'GAME' and 'GAME_WALLET' are TypeScript-level constraints
--   only (see activity-log.ts). No ALTER TABLE required.
--
-- Architecture note — Allowed Hardcodes:
--   Each provider's dedicated callback route (/api/games/megah5/callback,
--   /api/games/kiss918/callback, /api/mega/callback) contains ONE hardcoded
--   WHERE clause scoped to its own protocol entry point:
--     WHERE UPPER(p.code) = 'MEGAH5'   — megah5 protocol entry
--     WHERE UPPER(p.code) = '918KISS'  — kiss918 protocol entry
--     WHERE p.code = 'MEGAAPP'          — megaapp protocol entry
--   These are intentional Protocol Entry Hardcodes. Each callback URL is
--   protocol-specific and cannot be generic. They are NOT subject to the
--   Zero Hardcode principle and must NOT be changed.
--   All other provider-code comparisons in business logic ARE subject to
--   Zero Hardcode and must be eliminated in Phase 3 Tasks 4–10.
-- ═══════════════════════════════════════════════════════════════════════════════


-- ─── 1. Activity Timeline: trace_id ──────────────────────────────────────────
-- Enables the Activity Timeline principle: all events in one gaming session
-- (GAME_LAUNCH_START → Transfer → Bet → Win → Refund → Sync) share a single
-- trace_id so CS / Audit / Finance can query the full lifecycle at a glance.
--
-- Format (generated by GamingActivityService): GS-{yyyyMMdd}-{8 hex chars}
-- Example: GS-20260807-a3f9c12e
-- Nullable: non-gaming activities (DEPOSIT, WITHDRAWAL, etc.) leave it NULL.

ALTER TABLE member_activity_logs
  ADD COLUMN IF NOT EXISTS trace_id VARCHAR(40);

CREATE INDEX IF NOT EXISTS idx_mal_trace_id
  ON member_activity_logs (trace_id)
  WHERE trace_id IS NOT NULL;


-- ─── 2. Provider Metadata — MEGAAPP ──────────────────────────────────────────
-- wallet_type is omitted from metadata: it already exists as the authoritative
-- top-level column gp_providers.wallet_type (TRANSFER). Duplicating it in
-- metadata would create a second source of truth.
--
-- launch_mode: 'megaapp_dialog'  — shows the MEGA888 credentials dialog in ERP
-- ui_mode:     'modern'          — uses the new ERP provider settings UI
-- supports_game_picker: false    — MEGAAPP has no game picker (single-app)
-- supports_game_list:   false    — no game catalog API
-- supports_lobby_auth_test: false— no lobby URL to test
-- callback_protocol: 'megaapp_v1'— the legacy /api/mega/callback endpoint

UPDATE gp_providers
SET
  metadata = metadata || '{
    "ui_mode":                   "modern",
    "launch_mode":               "megaapp_dialog",
    "supports_game_picker":      false,
    "supports_game_list":        false,
    "supports_lobby_auth_test":  false,
    "callback_protocol":         "megaapp_v1"
  }'::jsonb,
  updated_at = NOW()
WHERE code = 'MEGAAPP';


-- ─── 3. Provider Metadata — MEGAH5 ───────────────────────────────────────────
-- launch_mode: 'webview'    — opens H5 lobby in an in-app browser / iframe
-- ui_mode:     'modern'
-- supports_game_picker: true    — MegaH5GamePicker dialog is active
-- supports_game_list:   true    — /api/games/settings/MEGAH5/sync works
-- supports_lobby_auth_test: false
-- callback_protocol: 'megah5_v1'— /api/games/megah5/callback/[action]

UPDATE gp_providers
SET
  metadata = metadata || '{
    "ui_mode":                   "modern",
    "launch_mode":               "webview",
    "supports_game_picker":      true,
    "supports_game_list":        true,
    "supports_lobby_auth_test":  false,
    "callback_protocol":         "megah5_v1"
  }'::jsonb,
  updated_at = NOW()
WHERE code = 'MEGAH5';


-- ─── 4. Provider Metadata — 918KISS / KISS918 ────────────────────────────────
-- ui_mode:     'legacy'         — uses the legacy-mode Settings/Credentials UI
--                                 (currently driven by isLegacy hardcode —
--                                  Phase 3 Task 6 will switch to reading this)
-- launch_mode: 'lobby'          — opens the 918KISS lobby URL directly
-- supports_game_picker: false   — no in-app game picker
-- supports_game_list:   false   — no game catalog API
-- supports_lobby_auth_test: true— has the H5 lobby auth test flow
--                                 (currently driven by provider code check —
--                                  Phase 3 Task 6 will switch to reading this)
-- callback_protocol: 'kiss918_v1'— /api/games/kiss918/callback/[action]

UPDATE gp_providers
SET
  metadata = metadata || '{
    "ui_mode":                   "legacy",
    "launch_mode":               "lobby",
    "supports_game_picker":      false,
    "supports_game_list":        false,
    "supports_lobby_auth_test":  true,
    "callback_protocol":         "kiss918_v1"
  }'::jsonb,
  updated_at = NOW()
WHERE UPPER(code) IN ('918KISS', 'KISS918');


-- ─── 5. Post-migration Validation ────────────────────────────────────────────
-- Run this SELECT after applying the migration to confirm all three providers
-- have the expected metadata. If any row shows metadata = '{}', the UPDATE above
-- found no matching row (provider not yet seeded — check gp_providers.code values).
--
-- Expected result:
--   code     | wallet_type | metadata.ui_mode | metadata.callback_protocol
--   ---------|-------------|------------------|--------------------------
--   MEGAAPP  | TRANSFER    | modern           | megaapp_v1
--   MEGAH5   | SEAMLESS    | modern           | megah5_v1
--   918KISS  | SEAMLESS    | legacy           | kiss918_v1
--
-- Validation query (run manually after migration):
--
-- SELECT
--   code,
--   wallet_type,
--   metadata->>'ui_mode'                 AS ui_mode,
--   metadata->>'launch_mode'             AS launch_mode,
--   metadata->>'callback_protocol'       AS callback_protocol,
--   (metadata->>'supports_game_picker')::boolean AS supports_game_picker,
--   (metadata->>'supports_lobby_auth_test')::boolean AS supports_lobby_auth_test
-- FROM gp_providers
-- WHERE code IN ('MEGAAPP', 'MEGAH5', '918KISS')
-- ORDER BY code;
--
-- Backward compatibility: trace_id column is nullable — all existing rows default
-- to NULL and are unaffected. All existing metadata '{}' rows are safely merged
-- with the || operator (no data lost).
